### ISSUE TITLE
Labels are not properly displayed on mac 

### ISSUE THREAD

**Issue by niqiukun** [AY1920S1-CS2103T-F11-3/main#81]
The following labels cannot be displayed entirely on mac:
 - [x] The password label on the side bar
![image](https://user-images.githubusercontent.com/5328196/67921409-8e4b7000-fbe2-11e9-9880-ad3b55d5d686.png)
 - [ ] The description label on the edit note panel
![image](https://user-images.githubusercontent.com/5328196/67921421-986d6e80-fbe2-11e9-86c0-59e2587bb3d7.png)

**Comment by hooncp** [comment]
Password mode fixed in #80
